{
 "title": "RPA Board",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful Jobs",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  started_at AS \"time\",\n  elapsed\nFROM test_run_status\n  JOIN test_runs ON test_runs.id=test_run_status.test_run_id"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "myorgid-simple-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Job count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM test_status\n"
    }
   ]
  },
  {
   "title": "Average time /task run",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 8 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(elapsed) AS \"elapsed\"\nFROM test_run_status\n"
    }
   ]
  }
 ]
}