{
 "title": "taxi_dashboard2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Drives total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(car_number)\nFROM taxi_drives\n"
    }
   ]
  },
  {
   "title": "Drives failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "Select \n   Count(CASE WHEN trip_succeeded=false  THEN 0 END) *100.0 / ((Select Count(car_number) From taxi_drives) * 1.00)\nFrom taxi_drives\n\n  \n"
    }
   ]
  },
  {
   "title": "Average length per ride",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(length) AS \"length\"\nFROM taxi_drives"
    }
   ]
  },
  {
   "title": "Average price per ride",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(price) AS \"price\"\nFROM taxi_drives\n"
    }
   ]
  },
  {
   "title": "Reasons for failed drives",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  reason_for_failure\nFROM taxi_drives\nWHERE\n  trip_succeeded = false"
    }
   ]
  }
 ]
}