{
 "title": "RPA Board",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  length\nFROM taxi_drives"
    }
   ]
  },
  {
   "title": "Average profit for ride",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(price) AS \"price\"\nFROM taxi_drives\n"
    }
   ]
  },
  {
   "title": "Average length per drive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(length) AS \"length\"\nFROM taxi_drives\n"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "myorgid-simple-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}